// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sys.proto

#include "sys.pb.h"
#include "sys.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace sys {

static const char* Sys_method_names[] = {
  "/sys.Sys/AddFolder",
  "/sys.Sys/Shutdown",
};

std::unique_ptr< Sys::Stub> Sys::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Sys::Stub> stub(new Sys::Stub(channel));
  return stub;
}

Sys::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_AddFolder_(Sys_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Shutdown_(Sys_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Sys::Stub::AddFolder(::grpc::ClientContext* context, const ::sys::FolderRequest& request, ::common::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sys::FolderRequest, ::common::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddFolder_, context, request, response);
}

void Sys::Stub::experimental_async::AddFolder(::grpc::ClientContext* context, const ::sys::FolderRequest* request, ::common::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sys::FolderRequest, ::common::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddFolder_, context, request, response, std::move(f));
}

void Sys::Stub::experimental_async::AddFolder(::grpc::ClientContext* context, const ::sys::FolderRequest* request, ::common::Empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddFolder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::common::Empty>* Sys::Stub::PrepareAsyncAddFolderRaw(::grpc::ClientContext* context, const ::sys::FolderRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::common::Empty, ::sys::FolderRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddFolder_, context, request);
}

::grpc::ClientAsyncResponseReader< ::common::Empty>* Sys::Stub::AsyncAddFolderRaw(::grpc::ClientContext* context, const ::sys::FolderRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddFolderRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Sys::Stub::Shutdown(::grpc::ClientContext* context, const ::common::Empty& request, ::common::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::common::Empty, ::common::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Shutdown_, context, request, response);
}

void Sys::Stub::experimental_async::Shutdown(::grpc::ClientContext* context, const ::common::Empty* request, ::common::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::common::Empty, ::common::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Shutdown_, context, request, response, std::move(f));
}

void Sys::Stub::experimental_async::Shutdown(::grpc::ClientContext* context, const ::common::Empty* request, ::common::Empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Shutdown_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::common::Empty>* Sys::Stub::PrepareAsyncShutdownRaw(::grpc::ClientContext* context, const ::common::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::common::Empty, ::common::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Shutdown_, context, request);
}

::grpc::ClientAsyncResponseReader< ::common::Empty>* Sys::Stub::AsyncShutdownRaw(::grpc::ClientContext* context, const ::common::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncShutdownRaw(context, request, cq);
  result->StartCall();
  return result;
}

Sys::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Sys_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Sys::Service, ::sys::FolderRequest, ::common::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Sys::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sys::FolderRequest* req,
             ::common::Empty* resp) {
               return service->AddFolder(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Sys_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Sys::Service, ::common::Empty, ::common::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Sys::Service* service,
             ::grpc::ServerContext* ctx,
             const ::common::Empty* req,
             ::common::Empty* resp) {
               return service->Shutdown(ctx, req, resp);
             }, this)));
}

Sys::Service::~Service() {
}

::grpc::Status Sys::Service::AddFolder(::grpc::ServerContext* context, const ::sys::FolderRequest* request, ::common::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Sys::Service::Shutdown(::grpc::ServerContext* context, const ::common::Empty* request, ::common::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sys

