// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: player.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Player {

  /// <summary>Holder for reflection information generated from player.proto</summary>
  public static partial class PlayerReflection {

    #region Descriptor
    /// <summary>File descriptor for player.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxwbGF5ZXIucHJvdG8SBnBsYXllchoMY29tbW9uLnByb3RvIkkKC1NvbmdS",
            "ZXF1ZXN0EgwKBHNvbmcYASABKAkSDQoFYWxidW0YAiABKAkSDgoGYXJ0aXN0",
            "GAMgASgJEg0KBWdlbnJlGAQgASgJIjgKDEFjdGlvblN0YXR1cxIoCgZzdGF0",
            "dXMYASABKA4yGC5wbGF5ZXIuQWN0aW9uU3RhdHVzRW51bSpNChBBY3Rpb25T",
            "dGF0dXNFbnVtEgYKAk9LEAASCgoGRkFJTEVEEAESEgoOSU5URVJOQUxfRVJS",
            "T1IQAhIRCg1SRVFVRVNUX0VSUk9SEAMyzwEKBlBsYXllchI3CghQbGF5U29u",
            "ZxITLnBsYXllci5Tb25nUmVxdWVzdBoULnBsYXllci5BY3Rpb25TdGF0dXMi",
            "ABItCgRQbGF5Eg0uY29tbW9uLkVtcHR5GhQucGxheWVyLkFjdGlvblN0YXR1",
            "cyIAEi4KBVBhdXNlEg0uY29tbW9uLkVtcHR5GhQucGxheWVyLkFjdGlvblN0",
            "YXR1cyIAEi0KBFN0b3ASDS5jb21tb24uRW1wdHkaFC5wbGF5ZXIuQWN0aW9u",
            "U3RhdHVzIgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Common.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Player.ActionStatusEnum), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Player.SongRequest), global::Player.SongRequest.Parser, new[]{ "Song", "Album", "Artist", "Genre" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Player.ActionStatus), global::Player.ActionStatus.Parser, new[]{ "Status" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ActionStatusEnum {
    [pbr::OriginalName("OK")] Ok = 0,
    [pbr::OriginalName("FAILED")] Failed = 1,
    [pbr::OriginalName("INTERNAL_ERROR")] InternalError = 2,
    [pbr::OriginalName("REQUEST_ERROR")] RequestError = 3,
  }

  #endregion

  #region Messages
  public sealed partial class SongRequest : pb::IMessage<SongRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SongRequest> _parser = new pb::MessageParser<SongRequest>(() => new SongRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SongRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Player.PlayerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SongRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SongRequest(SongRequest other) : this() {
      song_ = other.song_;
      album_ = other.album_;
      artist_ = other.artist_;
      genre_ = other.genre_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SongRequest Clone() {
      return new SongRequest(this);
    }

    /// <summary>Field number for the "song" field.</summary>
    public const int SongFieldNumber = 1;
    private string song_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Song {
      get { return song_; }
      set {
        song_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "album" field.</summary>
    public const int AlbumFieldNumber = 2;
    private string album_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Album {
      get { return album_; }
      set {
        album_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "artist" field.</summary>
    public const int ArtistFieldNumber = 3;
    private string artist_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Artist {
      get { return artist_; }
      set {
        artist_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "genre" field.</summary>
    public const int GenreFieldNumber = 4;
    private string genre_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Genre {
      get { return genre_; }
      set {
        genre_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SongRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SongRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Song != other.Song) return false;
      if (Album != other.Album) return false;
      if (Artist != other.Artist) return false;
      if (Genre != other.Genre) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Song.Length != 0) hash ^= Song.GetHashCode();
      if (Album.Length != 0) hash ^= Album.GetHashCode();
      if (Artist.Length != 0) hash ^= Artist.GetHashCode();
      if (Genre.Length != 0) hash ^= Genre.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Song.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Song);
      }
      if (Album.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Album);
      }
      if (Artist.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Artist);
      }
      if (Genre.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Genre);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Song.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Song);
      }
      if (Album.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Album);
      }
      if (Artist.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Artist);
      }
      if (Genre.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Genre);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Song.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Song);
      }
      if (Album.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Album);
      }
      if (Artist.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Artist);
      }
      if (Genre.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Genre);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SongRequest other) {
      if (other == null) {
        return;
      }
      if (other.Song.Length != 0) {
        Song = other.Song;
      }
      if (other.Album.Length != 0) {
        Album = other.Album;
      }
      if (other.Artist.Length != 0) {
        Artist = other.Artist;
      }
      if (other.Genre.Length != 0) {
        Genre = other.Genre;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Song = input.ReadString();
            break;
          }
          case 18: {
            Album = input.ReadString();
            break;
          }
          case 26: {
            Artist = input.ReadString();
            break;
          }
          case 34: {
            Genre = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Song = input.ReadString();
            break;
          }
          case 18: {
            Album = input.ReadString();
            break;
          }
          case 26: {
            Artist = input.ReadString();
            break;
          }
          case 34: {
            Genre = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ActionStatus : pb::IMessage<ActionStatus>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActionStatus> _parser = new pb::MessageParser<ActionStatus>(() => new ActionStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ActionStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Player.PlayerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActionStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActionStatus(ActionStatus other) : this() {
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActionStatus Clone() {
      return new ActionStatus(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::Player.ActionStatusEnum status_ = global::Player.ActionStatusEnum.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Player.ActionStatusEnum Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ActionStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ActionStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != global::Player.ActionStatusEnum.Ok) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Status != global::Player.ActionStatusEnum.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Status != global::Player.ActionStatusEnum.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status != global::Player.ActionStatusEnum.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ActionStatus other) {
      if (other == null) {
        return;
      }
      if (other.Status != global::Player.ActionStatusEnum.Ok) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::Player.ActionStatusEnum) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Status = (global::Player.ActionStatusEnum) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
