// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sys.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Sys {
  public static partial class Sys
  {
    static readonly string __ServiceName = "sys.Sys";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Sys.FolderRequest> __Marshaller_sys_FolderRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sys.FolderRequest.Parser));
    static readonly grpc::Marshaller<global::Common.Empty> __Marshaller_common_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Common.Empty.Parser));

    static readonly grpc::Method<global::Sys.FolderRequest, global::Common.Empty> __Method_AddFolder = new grpc::Method<global::Sys.FolderRequest, global::Common.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddFolder",
        __Marshaller_sys_FolderRequest,
        __Marshaller_common_Empty);

    static readonly grpc::Method<global::Common.Empty, global::Common.Empty> __Method_Shutdown = new grpc::Method<global::Common.Empty, global::Common.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Shutdown",
        __Marshaller_common_Empty,
        __Marshaller_common_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Sys.SysReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Sys</summary>
    [grpc::BindServiceMethod(typeof(Sys), "BindService")]
    public abstract partial class SysBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Common.Empty> AddFolder(global::Sys.FolderRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Common.Empty> Shutdown(global::Common.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Sys</summary>
    public partial class SysClient : grpc::ClientBase<SysClient>
    {
      /// <summary>Creates a new client for Sys</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SysClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Sys that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SysClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SysClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SysClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Common.Empty AddFolder(global::Sys.FolderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddFolder(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Common.Empty AddFolder(global::Sys.FolderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddFolder, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Common.Empty> AddFolderAsync(global::Sys.FolderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddFolderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Common.Empty> AddFolderAsync(global::Sys.FolderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddFolder, null, options, request);
      }
      public virtual global::Common.Empty Shutdown(global::Common.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Shutdown(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Common.Empty Shutdown(global::Common.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Shutdown, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Common.Empty> ShutdownAsync(global::Common.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ShutdownAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Common.Empty> ShutdownAsync(global::Common.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Shutdown, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SysClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SysClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SysBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddFolder, serviceImpl.AddFolder)
          .AddMethod(__Method_Shutdown, serviceImpl.Shutdown).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SysBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_AddFolder, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Sys.FolderRequest, global::Common.Empty>(serviceImpl.AddFolder));
      serviceBinder.AddMethod(__Method_Shutdown, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Common.Empty, global::Common.Empty>(serviceImpl.Shutdown));
    }

  }
}
#endregion
